server:
  port: 7000
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/bbinbin/cloudConfig
          username: xxxxxxxx
          password: xxxxxxxx
          basedir: D:\zookeeper\data\zookeeper
    zookeeper:
      connect-string: localhost:2181
  rabbitmq:
    virtual-host: /
    host: 127.0.0.1
    username: guest
    password: guest


